Repository Morphclue/code-camp-2, pull requests merged in 2022-07, with the labels that each got.

#71 Add user to database with hashed password
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
Labels: enhancement

#69 ProfileViewModel
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/UserBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/RepositoryModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AppPreference.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/ResourceProvider.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/BearerInterceptor.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/HomeView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/CommonTextField.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/PasswordTextField.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/ToastMessage.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/EditUserView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/IToast.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/UIText.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/feature/fox/coffee_counter/di/services/network/ApiServiceTest.kt
Labels: enhancement

#72 Remember Me
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AppPreference.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
Labels: enhancement

#73 Profileview - New look and logout
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#76 Add TransactionViewModel
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/DatabaseModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/feature/fox/coffee_counter/di/services/network/ApiServiceTest.kt
Labels: enhancement

#78 Add more Validation to AuthenticationView
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#75 Refresh bearer
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/BearerInterceptor.kt
Labels: enhancement

#79 UserList ViewModel
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/User.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/FundingBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/CommonTextField.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/LoadingAnimation.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/SearchBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/EditUserDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/EditUserView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/FundingDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#80 ViewModel: Item List
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#85 Close pop-up after adding User
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/AddUserDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
Labels: enhancement

#89 "previous response is still open" fix
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/BearerInterceptor.kt
Labels: bug

#100 fix: correct money amount in userList
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
Labels: bug, enhancement

#97 fix: remove double slash
  app/build.gradle
Labels: enhancement

#104 Feat: Buy Item with NFC Tags
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/ItemBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/AddItemDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ConfirmBuyDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/EditItemDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#98 Load and change profile picture
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Image.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/ImageResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileViewModel.kt
Labels: enhancement

#105 feat: Check if user is admin
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
Labels: enhancement

#107 Send money via QRCode
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/SendMoneyBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/QRCodeDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#109 Send money via a new money-button
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/SendMoneyDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#110 Add new users-endpoint
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
Labels: enhancement

#111 User Profiles
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
Labels: enhancement

#116 Refactor Navbar element positions
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
Labels: enhancement

#118 feat: Updated code to updated nfc tags (id saved instead of name)
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
Labels: enhancement

#112 Add an EditIcon to the profilePicture
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#121 FuzzySearch in UserList
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/SearchBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Utils.kt
Labels: enhancement

#123 Change icon of fab
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#120 Add statistics to TransactionView
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Color.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/DateTimeFormatter.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/worker/BalanceWorker.kt
  app/src/main/res/values/strings.xml
  build.gradle
  settings.gradle
Labels: enhancement, UI

#124 Sort users by username
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
Labels: enhancement

#117 Feat: Achievements
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Achievement.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/custom/Achievement.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AchievementGeneration.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/Notifications.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/AchievementOverview.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
  app/src/main/res/drawable/rich_bitch.png
  app/src/main/res/drawable/rookie_numbers.png
  app/src/main/res/drawable/the_one_percent.png
  app/src/main/res/drawable/weak_sleep.png
  app/src/main/res/values/strings.xml
Labels: enhancement

#125 Fix/item view fixes
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepositoryInt.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
Labels: bug

#126 fix: add init value if transations.size is zero
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
Labels: bug
