Repository Morphclue/code-camp-2, pull requests merged in 2022-08, with the labels that each got.

#128 Core Documentation
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AchievementGeneration.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AppPreference.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/BearerInterceptor.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/HomeView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavItem.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/CommonTextField.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/CustomButton.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/LoadingAnimation.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/MoneyAppBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/Notifications.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/PasswordTextField.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/SearchBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/ToastMessage.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Color.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Shape.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Theme.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Type.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/QRCodeDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/AddUserDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/FundingDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/SendMoneyDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UserListViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/DateTimeFormatter.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/IToast.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Resource.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/UIText.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Utils.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/worker/BalanceWorker.kt
Labels: documentation

#113 Refactor and optimize Code
  app/src/main/java/org/feature/fox/coffee_counter/data/local/ItemDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/relations/FundingsOfUser.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/relations/PurchasesOfUser.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Funding.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Item.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Purchase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/User.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/ItemBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/LoginBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/PurchaseBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/ItemResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/LoginResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/IItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/IUserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/DatabaseModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/MoneyAppBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/UIText.kt
Labels: enhancement

#130 Feat/refactor item list
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AchievementGeneration.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/AddItemDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ConfirmBuyDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/EditItemDialog.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Utils.kt
  app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#131 Logout
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
Labels: enhancement

#132 Fix pie chart of statistics view
  app/src/main/java/org/feature/fox/coffee_counter/data/local/ItemDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Achievement.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Funding.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Image.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Item.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Purchase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/User.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/FundingBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/ItemBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/LoginBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/PurchaseBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/SendMoneyBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/UserBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/ImageResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/ItemResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/LoginResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/TransactionResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserIdResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/IItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/IUserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
Labels: bug, UI

#134 App-icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#133 Personalization
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#135 Fix/fix and optimize itemlist
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsViewModel.kt
Labels: bug
