Repository Morphclue/code-camp-2, pull requests merged in 2022-06, with the labels that each got.

#33 Add db for purchase and funding
  app/src/androidTest/java/org/feature/fox/coffee_counter/data/local/dao/ItemDaoTest.kt
  app/src/androidTest/java/org/feature/fox/coffee_counter/data/local/dao/UserDaoTest.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/ItemDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/relations/FundingAndUser.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/relations/PurchaseAndUser.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Funding.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Item.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/Purchase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/tables/User.kt
Labels: enhancement

#39 Add User-List
  app/src/main/java/org/feature/fox/coffee_counter/ui/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/SearchBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/UsersView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#44 Add issue-templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#45 UI: Add TopBar with title
  app/src/main/java/org/feature/fox/coffee_counter/ui/HistoryView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/MoneyAppBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/UsersView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#46 Add item repository
  app/src/main/java/org/feature/fox/coffee_counter/data/local/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepositoryInt.kt
Labels: enhancement

#43 UI: TransactionView / HistoryView
  app/src/main/java/org/feature/fox/coffee_counter/ui/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/HistoryView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#50 Bump gradle version 7.2.0 -> 7.2.1
  build.gradle
Labels: enhancement

#51 UI: EditUserView
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/ui/EditUserView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/UsersView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#52 Update dependencies
  app/build.gradle
Labels: enhancement

#53 Add usesCleartextTraffic
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: enhancement

#47 Add User Repository
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepositoryInt.kt
Labels: enhancement

#49 Refactor: Navbar
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/ui/BottomNavItem.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/BottomNavigationView.kt
Labels: enhancement

#62 Refactor: Move dao to database package
  app/src/androidTest/java/org/feature/fox/coffee_counter/data/local/dao/ItemDaoTest.kt
  app/src/androidTest/java/org/feature/fox/coffee_counter/data/local/dao/UserDaoTest.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/ItemDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/UserDatabase.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/ItemDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/local/database/dao/UserDao.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/ItemRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
Labels: enhancement

#63 Refactor: Move Constants to build script, add timbers library
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Constants.kt
  app/src/test/java/org/feature/fox/coffee_counter/di/services/network/ApiServiceTest.kt
Labels: enhancement

#61 Refactor: BottomNavbar
  app/src/main/java/org/feature/fox/coffee_counter/ui/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/ItemsView.kt
Labels: enhancement

#64 Authentication ViewModel Core
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/DatabaseModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/RepositoryModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/BearerInterceptor.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/HomeView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavItem.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/BottomNavigationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/CustomButton.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/MoneyAppBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/common/SearchBar.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/items/ItemsView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/profile/ProfileView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/transaction/TransactionView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/EditUserView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/user/UsersView.kt
Labels: enhancement

#66 Authentication viewmodel - Login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/ui/CoreActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
Labels: enhancement

#67 Add PreferenceManager
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/di/services/AppPreference.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
Labels: enhancement

#68 Complete AuthViewModel-core
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/repository/UserRepository.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/ResourceProvider.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/authentication/AuthenticationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement
