Repository Morphclue/code-camp-2, pull requests merged in 2022-05, with the labels that each got.

#1 Configure Hilt and bumb dependencies
  app/build.gradle
  app/src/androidTest/java/org/feature/fox/coffee_counter/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/feature/fox/coffee_counter/AppModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/BaseApplication.kt
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Shape.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Theme.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Type.kt
  app/src/test/java/org/feature/fox/coffee_counter/ExampleUnitTest.kt
  build.gradle
Labels: enhancement

#2 Added additional dependencies for setup
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: enhancement

#17 UI: Add HomeScreen
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/MainActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/HomeScreen.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Color.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/theme/Theme.kt
  app/src/main/res/drawable/coffee.png
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#26 Chore: Bump Gradle version
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#27 Add schemas to .gitignore
  .gitignore
Labels: enhancement, question

#28 UI: Add RegisterView
  app/src/main/java/org/feature/fox/coffee_counter/AuthenticationActivity.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/AuthenticationView.kt
  app/src/main/java/org/feature/fox/coffee_counter/ui/HomeView.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, UI

#29 Add all api routes without authentication
  app/build.gradle
  app/src/main/java/org/feature/fox/coffee_counter/data/local/User.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/LoginBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/body/UserBody.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/ItemResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/LoginResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/data/models/response/UserResponse.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/module/ApiModule.kt
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Constants.kt
  app/src/main/java/org/feature/fox/coffee_counter/util/Resource.kt
  app/src/test/java/org/feature/fox/coffee_counter/di/services/network/ApiServiceTest.kt
  app/src/test/resources/json/200-get-item-by-id.json
  app/src/test/resources/json/200-get-items.json
  app/src/test/resources/json/200-get-users.json
  app/src/test/resources/json/200-post-login.json
Labels: enhancement

#32 Fix typo at ApiService
  app/src/main/java/org/feature/fox/coffee_counter/di/services/network/ApiService.kt
  app/src/test/java/org/feature/fox/coffee_counter/di/services/network/ApiServiceTest.kt
Labels: documentation
